export const cars = [
    {
        id: 1,
        img: "https://ronbrooks.b-cdn.net/wp-content/uploads/2023/06/toyota-supra-mk4.png",
        title: "Best of th best",
        time: "4:15",
        followers: "27m views",
        date: "1 hours ago",
        username: "ＷＨＩＴＥɸ",
    },
    {
        id: 2,
        img: "https://cars.usnews.com/static/images/Auto/izmo/i159615313/2023_bmw_5_series_angularfront.jpg",
        title: "BMW",
        time: "4:15",
        followers: "57k views",
        date: "2 weeks ago",
        username: "ＷＨＩＴＥɸ",
    },
    {
        id: 3,
        img: "https://ev-database.org/img/auto/BMW_i5_eDrive40_Sedan/BMW_i5_eDrive40_Sedan-01.jpg",
        title: "BMW i5 eDrive Sedan",
        time: "4:15",
        followers: "39m views",
        date: "2 month ago",
        username: "ＷＨＩＴＥɸ",
    },
    {
        id: 4,
        img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSnWblUXEz6fvkxKrMs8BWtlNA5s_0JYTRVThfg6zs_cBTmgQD_A3tZQbti7QXveqV2WvA&usqp=CAU",
        title: "Lamborghini Hybrid",
        time: "4:15",
        followers: "9.8m views",
        date: "29 days ago",
        username: "ＷＨＩＴＥɸ",
    },
     {
        id: 5,
        img: "https://www.bmw-me.com/content/dam/bmw/common/topics/offers-and-services/bmw-special-sales-2020/protection-vehicle/bmw-css-7-series-protection-ms-new-standard.jpg",
        title: "BMWM",
        time: "4:15",
        followers: "1.7m views",
        date: "1 month ago",
        username: "ＷＨＩＴＥɸ",
    },
]