export const favariteDate = [
    {
        id: 1,
        img: "https://ronbrooks.b-cdn.net/wp-content/uploads/2023/06/toyota-supra-mk4.png",
        title: "Best of th best",
        time: "4:15",
        followers: "27m views",
        date: "1 hours ago",
        username: "ＷＨＩＴＥɸ",
    },
    {
        id: 2,
        img: "https://i.ytimg.com/vi/QJsvH7pR6ZM/sddefault.jpg",
        title: "Magic city",
        time: "4:15",
        followers: "57k views",
        date: "2 weeks ago",
        username: "ＷＨＩＴＥɸ",
    },
    {
        id: 3,
        img: "https://ev-database.org/img/auto/BMW_i5_eDrive40_Sedan/BMW_i5_eDrive40_Sedan-01.jpg",
        title: "BMW i5 eDrive Sedan",
        time: "4:15",
        followers: "39m views",
        date: "2 month ago",
        username: "ＷＨＩＴＥɸ",
    },
    {
        id: 4,
        img: "https://i.ytimg.com/vi/Gm149OxyJtA/maxresdefault.jpg",
        title: "Java",
        time: "4:15",
        followers: "9.8m views",
        date: "29 days ago",
        username: "ＷＨＩＴＥɸ",
    },
     {
        id: 5,
        img: "https://i.ytimg.com/vi/p1r-M5BVaMo/maxresdefault.jpg",
        title: "Amir Temur istirohat bog'i",
        time: "4:15",
        followers: "1.7m views",
        date: "1 month ago",
        username: "ＷＨＩＴＥɸ",
    },
];