export const favariteDate = [
    {
        id: 1,
        img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSSW8C-9MTaQiNJF0R-HKg579Q9ST696n8wxCSjT2wEpg&s",
        title: "Mers",
        time: "6:36",
        followers: "27m views",
        date: "1 hours ago",
        username: "_Bobojon_",
    },
    {
        id: 2,
        img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR1VD_oUL3n1zHigzHKJIov0Ia7Ou_PKjkJvAon7Ms9Eg&s",
        title: "Gelik",
        time: "6:36",
        followers: "39m views",
        date: "2 month ago",
        username: "_Bobojon_",
    },
    {
        id: 3,
        img: "https://it-park.uz/storage/images/news/normal/92F8NALKfBu1iJugNTBJFDbph6321qnvdLiOUfBD.jpeg",
        title: "Xorazm it park",
        time: "6:36",
        followers: "1.7m views",
        date: "1 month ago",
        username: "_Bobojon_",
    },
    {
        id: 4,
        img: "https://i.ytimg.com/vi/Gm149OxyJtA/maxresdefault.jpg",
        title: "Java",
        time: "6:36",
        followers: "9.8m views",
        date: "29 days ago",
        username: "_Bobojon_",
    },
    {
        id: 5,
        img: "https://i.ytimg.com/vi/QJsvH7pR6ZM/sddefault.jpg",
        title: "Magic city",
        time: "6:36",
        followers: "57k views",
        date: "2 weeks ago",
        username: "_Bobojon_",
    },
];